server:
#  port: 8080
  context-path: /rest

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    platform: h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework: INFO