DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE COIN_TABLE(COIN_ID VARCHAR(15) PRIMARY KEY,COIN_TYPE VARCHAR(50),
 COIN_VALUE BIGINT, CREATED_BY VARCHAR(50), MODIFIED_BY VARCHAR(50), CREATED_DATE  DATE, MODIFIED_DATE DATE);

INSERT INTO COIN_TABLE(COIN_ID, COIN_TYPE, COIN_VALUE, CREATED_BY, MODIFIED_BY, CREATED_DATE, MODIFIED_DATE)
VALUES (1, 'Q', 100, 'ROHIT', NULL, '2022-02-11', NULL);
INSERT INTO COIN_TABLE (COIN_ID, COIN_TYPE, COIN_VALUE, CREATED_BY, MODIFIED_BY, CREATED_DATE, MODIFIED_DATE)
VALUES (2, 'D', 100, 'ROHIT', NULL, '2022-02-11', NULL);
INSERT INTO COIN_TABLE (COIN_ID, COIN_TYPE, COIN_VALUE, CREATED_BY, MODIFIED_BY, CREATED_DATE, MODIFIED_DATE)
VALUES (3, 'N', 100, 'ROHIT', NULL, '2022-02-11', NULL);
INSERT INTO COIN_TABLE (COIN_ID, COIN_TYPE, COIN_VALUE, CREATED_BY, MODIFIED_BY, CREATED_DATE, MODIFIED_DATE)
VALUES (4, 'P', 100, 'ROHIT', NULL, '2022-02-11', NULL);