DROP TABLE IF EXISTS COIN;
CREATE TABLE COIN(COIN_ID INT PRIMARY KEY,COIN_COUNT INT NOT NULL,COIN_TYPE VARCHAR(30));
INSERT INTO COIN(COIN_ID,COIN_COUNT,COIN_TYPE) VALUES(1,100,'Q');
INSERT INTO COIN(COIN_ID,COIN_COUNT,COIN_TYPE) VALUES(2,100,'D');
INSERT INTO COIN(COIN_ID,COIN_COUNT,COIN_TYPE) VALUES(3,100,'N');
INSERT INTO COIN(COIN_ID,COIN_COUNT,COIN_TYPE) VALUES(4,100,'P');
